//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	if in.DatabaseBackup != nil {
		in, out := &in.DatabaseBackup, &out.DatabaseBackup
		*out = new(DatabaseBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(Concurrency)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Concurrency) DeepCopyInto(out *Concurrency) {
	*out = *in
	if in.Thumbnail != nil {
		in, out := &in.Thumbnail, &out.Thumbnail
		*out = new(int32)
		**out = **in
	}
	if in.MetadataExtraction != nil {
		in, out := &in.MetadataExtraction, &out.MetadataExtraction
		*out = new(int32)
		**out = **in
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(int32)
		**out = **in
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(int32)
		**out = **in
	}
	if in.SmartSearch != nil {
		in, out := &in.SmartSearch, &out.SmartSearch
		*out = new(int32)
		**out = **in
	}
	if in.FaceDetection != nil {
		in, out := &in.FaceDetection, &out.FaceDetection
		*out = new(int32)
		**out = **in
	}
	if in.VideoConversion != nil {
		in, out := &in.VideoConversion, &out.VideoConversion
		*out = new(int32)
		**out = **in
	}
	if in.Migration != nil {
		in, out := &in.Migration, &out.Migration
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Concurrency.
func (in *Concurrency) DeepCopy() *Concurrency {
	if in == nil {
		return nil
	}
	out := new(Concurrency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseBackup) DeepCopyInto(out *DatabaseBackup) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(string)
		**out = **in
	}
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseBackup.
func (in *DatabaseBackup) DeepCopy() *DatabaseBackup {
	if in == nil {
		return nil
	}
	out := new(DatabaseBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Immich) DeepCopyInto(out *Immich) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Immich.
func (in *Immich) DeepCopy() *Immich {
	if in == nil {
		return nil
	}
	out := new(Immich)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Immich) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmichList) DeepCopyInto(out *ImmichList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Immich, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmichList.
func (in *ImmichList) DeepCopy() *ImmichList {
	if in == nil {
		return nil
	}
	out := new(ImmichList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImmichList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmichSpec) DeepCopyInto(out *ImmichSpec) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(Application)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmichSpec.
func (in *ImmichSpec) DeepCopy() *ImmichSpec {
	if in == nil {
		return nil
	}
	out := new(ImmichSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmichStatus) DeepCopyInto(out *ImmichStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmichStatus.
func (in *ImmichStatus) DeepCopy() *ImmichStatus {
	if in == nil {
		return nil
	}
	out := new(ImmichStatus)
	in.DeepCopyInto(out)
	return out
}
