//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	if in.ExternalDomain != nil {
		in, out := &in.ExternalDomain, &out.ExternalDomain
		*out = new(string)
		**out = **in
	}
	if in.WelcomeMessage != nil {
		in, out := &in.WelcomeMessage, &out.WelcomeMessage
		*out = new(string)
		**out = **in
	}
	if in.CustomCSS != nil {
		in, out := &in.CustomCSS, &out.CustomCSS
		*out = new(string)
		**out = **in
	}
	if in.OAuthLogin != nil {
		in, out := &in.OAuthLogin, &out.OAuthLogin
		*out = new(OAuthLogin)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordLoginEnabled != nil {
		in, out := &in.PasswordLoginEnabled, &out.PasswordLoginEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseBackup != nil {
		in, out := &in.DatabaseBackup, &out.DatabaseBackup
		*out = new(DatabaseBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageSettings != nil {
		in, out := &in.ImageSettings, &out.ImageSettings
		*out = new(ImageSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.VideoTranscodingSettings != nil {
		in, out := &in.VideoTranscodingSettings, &out.VideoTranscodingSettings
		*out = new(VideoTranscodingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.JobConcurrency != nil {
		in, out := &in.JobConcurrency, &out.JobConcurrency
		*out = new(JobConcurrency)
		(*in).DeepCopyInto(*out)
	}
	if in.MetadataFaceImportEnabled != nil {
		in, out := &in.MetadataFaceImportEnabled, &out.MetadataFaceImportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExternalLibraryScanning != nil {
		in, out := &in.ExternalLibraryScanning, &out.ExternalLibraryScanning
		*out = new(ExternalLibraryScanningSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(Logging)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineLearning != nil {
		in, out := &in.MachineLearning, &out.MachineLearning
		*out = new(MachineLearning)
		(*in).DeepCopyInto(*out)
	}
	if in.MapEnabled != nil {
		in, out := &in.MapEnabled, &out.MapEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MapReverseGeocodingEnabled != nil {
		in, out := &in.MapReverseGeocodingEnabled, &out.MapReverseGeocodingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MapLightStyleURL != nil {
		in, out := &in.MapLightStyleURL, &out.MapLightStyleURL
		*out = new(string)
		**out = **in
	}
	if in.MapDarkStyleURL != nil {
		in, out := &in.MapDarkStyleURL, &out.MapDarkStyleURL
		*out = new(string)
		**out = **in
	}
	if in.EmailNotifications != nil {
		in, out := &in.EmailNotifications, &out.EmailNotifications
		*out = new(EmailNotifications)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageTemplateEnabled != nil {
		in, out := &in.StorageTemplateEnabled, &out.StorageTemplateEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageTemplateHashVerificationEnabled != nil {
		in, out := &in.StorageTemplateHashVerificationEnabled, &out.StorageTemplateHashVerificationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageTemplateTemplate != nil {
		in, out := &in.StorageTemplateTemplate, &out.StorageTemplateTemplate
		*out = new(string)
		**out = **in
	}
	if in.ExperimentalSettings != nil {
		in, out := &in.ExperimentalSettings, &out.ExperimentalSettings
		*out = new(ExperimentalSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TrashEnabled != nil {
		in, out := &in.TrashEnabled, &out.TrashEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TrashTTLDays != nil {
		in, out := &in.TrashTTLDays, &out.TrashTTLDays
		*out = new(int32)
		**out = **in
	}
	if in.UserDeleteTTLDays != nil {
		in, out := &in.UserDeleteTTLDays, &out.UserDeleteTTLDays
		*out = new(bool)
		**out = **in
	}
	if in.VersionCheckEnabled != nil {
		in, out := &in.VersionCheckEnabled, &out.VersionCheckEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioCodec) DeepCopyInto(out *AudioCodec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioCodec.
func (in *AudioCodec) DeepCopy() *AudioCodec {
	if in == nil {
		return nil
	}
	out := new(AudioCodec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseBackup) DeepCopyInto(out *DatabaseBackup) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(string)
		**out = **in
	}
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseBackup.
func (in *DatabaseBackup) DeepCopy() *DatabaseBackup {
	if in == nil {
		return nil
	}
	out := new(DatabaseBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailNotifications) DeepCopyInto(out *EmailNotifications) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ServerHostSecretKeyRef != nil {
		in, out := &in.ServerHostSecretKeyRef, &out.ServerHostSecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ServerPort != nil {
		in, out := &in.ServerPort, &out.ServerPort
		*out = new(int32)
		**out = **in
	}
	if in.SkipCertificateChecks != nil {
		in, out := &in.SkipCertificateChecks, &out.SkipCertificateChecks
		*out = new(bool)
		**out = **in
	}
	if in.UsernameSecretKeyRef != nil {
		in, out := &in.UsernameSecretKeyRef, &out.UsernameSecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PasswordSecretKeyRef != nil {
		in, out := &in.PasswordSecretKeyRef, &out.PasswordSecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.FromAddressSecretKeyRef != nil {
		in, out := &in.FromAddressSecretKeyRef, &out.FromAddressSecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailNotifications.
func (in *EmailNotifications) DeepCopy() *EmailNotifications {
	if in == nil {
		return nil
	}
	out := new(EmailNotifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExperimentalSettings) DeepCopyInto(out *ExperimentalSettings) {
	*out = *in
	if in.WatchExternalLibrary != nil {
		in, out := &in.WatchExternalLibrary, &out.WatchExternalLibrary
		*out = new(bool)
		**out = **in
	}
	if in.HardwareAcceleration != nil {
		in, out := &in.HardwareAcceleration, &out.HardwareAcceleration
		*out = new(HardwareAcceleration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExperimentalSettings.
func (in *ExperimentalSettings) DeepCopy() *ExperimentalSettings {
	if in == nil {
		return nil
	}
	out := new(ExperimentalSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalLibraryScanningSettings) DeepCopyInto(out *ExternalLibraryScanningSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalLibraryScanningSettings.
func (in *ExternalLibraryScanningSettings) DeepCopy() *ExternalLibraryScanningSettings {
	if in == nil {
		return nil
	}
	out := new(ExternalLibraryScanningSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareAcceleration) DeepCopyInto(out *HardwareAcceleration) {
	*out = *in
	if in.AccelerationAPI != nil {
		in, out := &in.AccelerationAPI, &out.AccelerationAPI
		*out = new(string)
		**out = **in
	}
	if in.HardwareDecodingEnabled != nil {
		in, out := &in.HardwareDecodingEnabled, &out.HardwareDecodingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConstantQualityMode != nil {
		in, out := &in.ConstantQualityMode, &out.ConstantQualityMode
		*out = new(string)
		**out = **in
	}
	if in.TemporalAQEnabled != nil {
		in, out := &in.TemporalAQEnabled, &out.TemporalAQEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PreferredHardwareDevice != nil {
		in, out := &in.PreferredHardwareDevice, &out.PreferredHardwareDevice
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareAcceleration.
func (in *HardwareAcceleration) DeepCopy() *HardwareAcceleration {
	if in == nil {
		return nil
	}
	out := new(HardwareAcceleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSettings) DeepCopyInto(out *ImageSettings) {
	*out = *in
	if in.ThumbnailFormat != nil {
		in, out := &in.ThumbnailFormat, &out.ThumbnailFormat
		*out = new(string)
		**out = **in
	}
	if in.ThumbnailResolution != nil {
		in, out := &in.ThumbnailResolution, &out.ThumbnailResolution
		*out = new(int32)
		**out = **in
	}
	if in.ThumbnailQuality != nil {
		in, out := &in.ThumbnailQuality, &out.ThumbnailQuality
		*out = new(int32)
		**out = **in
	}
	if in.PreviewFormat != nil {
		in, out := &in.PreviewFormat, &out.PreviewFormat
		*out = new(string)
		**out = **in
	}
	if in.PreviewResolution != nil {
		in, out := &in.PreviewResolution, &out.PreviewResolution
		*out = new(int32)
		**out = **in
	}
	if in.PreviewQuality != nil {
		in, out := &in.PreviewQuality, &out.PreviewQuality
		*out = new(int32)
		**out = **in
	}
	if in.P3ColorSpaceEnabled != nil {
		in, out := &in.P3ColorSpaceEnabled, &out.P3ColorSpaceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EmbeddedPreviewEnabled != nil {
		in, out := &in.EmbeddedPreviewEnabled, &out.EmbeddedPreviewEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSettings.
func (in *ImageSettings) DeepCopy() *ImageSettings {
	if in == nil {
		return nil
	}
	out := new(ImageSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Immich) DeepCopyInto(out *Immich) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Immich.
func (in *Immich) DeepCopy() *Immich {
	if in == nil {
		return nil
	}
	out := new(Immich)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Immich) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmichList) DeepCopyInto(out *ImmichList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Immich, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmichList.
func (in *ImmichList) DeepCopy() *ImmichList {
	if in == nil {
		return nil
	}
	out := new(ImmichList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImmichList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmichSpec) DeepCopyInto(out *ImmichSpec) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(Application)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmichSpec.
func (in *ImmichSpec) DeepCopy() *ImmichSpec {
	if in == nil {
		return nil
	}
	out := new(ImmichSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmichStatus) DeepCopyInto(out *ImmichStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmichStatus.
func (in *ImmichStatus) DeepCopy() *ImmichStatus {
	if in == nil {
		return nil
	}
	out := new(ImmichStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobConcurrency) DeepCopyInto(out *JobConcurrency) {
	*out = *in
	if in.Thumbnail != nil {
		in, out := &in.Thumbnail, &out.Thumbnail
		*out = new(int32)
		**out = **in
	}
	if in.MetadataExtraction != nil {
		in, out := &in.MetadataExtraction, &out.MetadataExtraction
		*out = new(int32)
		**out = **in
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(int32)
		**out = **in
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(int32)
		**out = **in
	}
	if in.SmartSearch != nil {
		in, out := &in.SmartSearch, &out.SmartSearch
		*out = new(int32)
		**out = **in
	}
	if in.FaceDetection != nil {
		in, out := &in.FaceDetection, &out.FaceDetection
		*out = new(int32)
		**out = **in
	}
	if in.VideoConversion != nil {
		in, out := &in.VideoConversion, &out.VideoConversion
		*out = new(int32)
		**out = **in
	}
	if in.Migration != nil {
		in, out := &in.Migration, &out.Migration
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobConcurrency.
func (in *JobConcurrency) DeepCopy() *JobConcurrency {
	if in == nil {
		return nil
	}
	out := new(JobConcurrency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLearning) DeepCopyInto(out *MachineLearning) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ServerURL != nil {
		in, out := &in.ServerURL, &out.ServerURL
		*out = new(string)
		**out = **in
	}
	if in.SmartSearchEnabled != nil {
		in, out := &in.SmartSearchEnabled, &out.SmartSearchEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SmartSearchClipModelName != nil {
		in, out := &in.SmartSearchClipModelName, &out.SmartSearchClipModelName
		*out = new(string)
		**out = **in
	}
	if in.DuplicateDetectionEnabled != nil {
		in, out := &in.DuplicateDetectionEnabled, &out.DuplicateDetectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DuplicateMaxDistance != nil {
		in, out := &in.DuplicateMaxDistance, &out.DuplicateMaxDistance
		*out = new(string)
		**out = **in
	}
	if in.FacialRecognitionEnabled != nil {
		in, out := &in.FacialRecognitionEnabled, &out.FacialRecognitionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FacialRecognitionModelName != nil {
		in, out := &in.FacialRecognitionModelName, &out.FacialRecognitionModelName
		*out = new(string)
		**out = **in
	}
	if in.FacialRecognitionMinScore != nil {
		in, out := &in.FacialRecognitionMinScore, &out.FacialRecognitionMinScore
		*out = new(string)
		**out = **in
	}
	if in.FacialRecognitionMaxDistance != nil {
		in, out := &in.FacialRecognitionMaxDistance, &out.FacialRecognitionMaxDistance
		*out = new(string)
		**out = **in
	}
	if in.FacialRecognitionMinFaces != nil {
		in, out := &in.FacialRecognitionMinFaces, &out.FacialRecognitionMinFaces
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLearning.
func (in *MachineLearning) DeepCopy() *MachineLearning {
	if in == nil {
		return nil
	}
	out := new(MachineLearning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthLogin) DeepCopyInto(out *OAuthLogin) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IssuerUrl != nil {
		in, out := &in.IssuerUrl, &out.IssuerUrl
		*out = new(string)
		**out = **in
	}
	if in.ClientIdSecretKeyRef != nil {
		in, out := &in.ClientIdSecretKeyRef, &out.ClientIdSecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ClientSecretSecretKeyRef != nil {
		in, out := &in.ClientSecretSecretKeyRef, &out.ClientSecretSecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.ProfileSigningAlgorithm != nil {
		in, out := &in.ProfileSigningAlgorithm, &out.ProfileSigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.StorageLabelClaim != nil {
		in, out := &in.StorageLabelClaim, &out.StorageLabelClaim
		*out = new(string)
		**out = **in
	}
	if in.StorageQuotaClaim != nil {
		in, out := &in.StorageQuotaClaim, &out.StorageQuotaClaim
		*out = new(string)
		**out = **in
	}
	if in.DefaultStorageQuota != nil {
		in, out := &in.DefaultStorageQuota, &out.DefaultStorageQuota
		*out = new(int)
		**out = **in
	}
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.AutoRegister != nil {
		in, out := &in.AutoRegister, &out.AutoRegister
		*out = new(bool)
		**out = **in
	}
	if in.AutoLaunch != nil {
		in, out := &in.AutoLaunch, &out.AutoLaunch
		*out = new(bool)
		**out = **in
	}
	if in.MobileRedirectUri != nil {
		in, out := &in.MobileRedirectUri, &out.MobileRedirectUri
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthLogin.
func (in *OAuthLogin) DeepCopy() *OAuthLogin {
	if in == nil {
		return nil
	}
	out := new(OAuthLogin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoCodec) DeepCopyInto(out *VideoCodec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoCodec.
func (in *VideoCodec) DeepCopy() *VideoCodec {
	if in == nil {
		return nil
	}
	out := new(VideoCodec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoContainer) DeepCopyInto(out *VideoContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoContainer.
func (in *VideoContainer) DeepCopy() *VideoContainer {
	if in == nil {
		return nil
	}
	out := new(VideoContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoTranscodingSettings) DeepCopyInto(out *VideoTranscodingSettings) {
	*out = *in
	if in.ConstantRateFactor != nil {
		in, out := &in.ConstantRateFactor, &out.ConstantRateFactor
		*out = new(int32)
		**out = **in
	}
	if in.CompressionSpeed != nil {
		in, out := &in.CompressionSpeed, &out.CompressionSpeed
		*out = new(string)
		**out = **in
	}
	if in.VideoCodec != nil {
		in, out := &in.VideoCodec, &out.VideoCodec
		*out = new(VideoCodec)
		**out = **in
	}
	if in.AudioCodec != nil {
		in, out := &in.AudioCodec, &out.AudioCodec
		*out = new(AudioCodec)
		**out = **in
	}
	if in.AcceptedVideoCodecs != nil {
		in, out := &in.AcceptedVideoCodecs, &out.AcceptedVideoCodecs
		*out = new([]VideoCodec)
		if **in != nil {
			in, out := *in, *out
			*out = make([]VideoCodec, len(*in))
			copy(*out, *in)
		}
	}
	if in.AcceptedAudioCodecs != nil {
		in, out := &in.AcceptedAudioCodecs, &out.AcceptedAudioCodecs
		*out = new([]AudioCodec)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AudioCodec, len(*in))
			copy(*out, *in)
		}
	}
	if in.AcceptedContainers != nil {
		in, out := &in.AcceptedContainers, &out.AcceptedContainers
		*out = new([]VideoContainer)
		if **in != nil {
			in, out := *in, *out
			*out = make([]VideoContainer, len(*in))
			copy(*out, *in)
		}
	}
	if in.TargetResolution != nil {
		in, out := &in.TargetResolution, &out.TargetResolution
		*out = new(string)
		**out = **in
	}
	if in.MaxBitrate != nil {
		in, out := &in.MaxBitrate, &out.MaxBitrate
		*out = new(string)
		**out = **in
	}
	if in.Threads != nil {
		in, out := &in.Threads, &out.Threads
		*out = new(int32)
		**out = **in
	}
	if in.TranscodePolicy != nil {
		in, out := &in.TranscodePolicy, &out.TranscodePolicy
		*out = new(string)
		**out = **in
	}
	if in.ToneMappingAlgorithm != nil {
		in, out := &in.ToneMappingAlgorithm, &out.ToneMappingAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.TwoPassEncodingEnabled != nil {
		in, out := &in.TwoPassEncodingEnabled, &out.TwoPassEncodingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MaximumBFrames != nil {
		in, out := &in.MaximumBFrames, &out.MaximumBFrames
		*out = new(int32)
		**out = **in
	}
	if in.ReferenceFrames != nil {
		in, out := &in.ReferenceFrames, &out.ReferenceFrames
		*out = new(int32)
		**out = **in
	}
	if in.MaximumKFrameInterval != nil {
		in, out := &in.MaximumKFrameInterval, &out.MaximumKFrameInterval
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoTranscodingSettings.
func (in *VideoTranscodingSettings) DeepCopy() *VideoTranscodingSettings {
	if in == nil {
		return nil
	}
	out := new(VideoTranscodingSettings)
	in.DeepCopyInto(out)
	return out
}
